# Generated by Django 3.1.7 on 2021-04-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price_number',
            field=models.FloatField(),
        ),
    ]
