# Generated by Django 3.1.7 on 2021-04-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210402_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='prod_name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='med_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.medicine'),
            preserve_default=False,
        ),
    ]
