# Generated by Django 3.2 on 2021-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210402_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
