# Generated by Django 3.2 on 2021-04-27 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_auto_20210427_0530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminProfile',
            new_name='Profile',
        ),
    ]
